name: she_connect
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


#  flutter_lints: ^1.0.4
  custom_navigation_bar: ^0.8.2
  tab_indicator_styler: ^2.0.0
  carousel_slider: ^4.1.1
  carousel_pro: ^1.0.0
  flutter_svg:
  razorpay_flutter: ^1.3.0
  fluttertoast: ^8.0.9
  lottie: ^1.3.0
  pin_code_fields: ^7.4.0
  sms_autofill: ^2.2.0
  timer_button: ^2.0.0
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  share: ^2.0.4
  http:
  flutter_spinkit: ^5.1.0
  shared_preferences:
  email_validator: ^2.0.1
  image_picker:
  dio: ^4.0.6
  provider: ^6.0.3
  banner_carousel: ^1.2.1
  flutter_svg_provider: ^1.0.3
  flutter_html:
  url_launcher:
  badges: ^2.0.3
  syncfusion_flutter_sliders: ^20.1.61
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  get:
  http_parser: ^4.0.1


  geolocator:
  geocoding: ^2.0.4

  firebase: ^9.0.3
  firebase_core: ^1.20.0
  flutter_local_notifications:
  firebase_messaging: ^11.4.2
  firebase_dynamic_links: ^2.0.6
  flutter_sound: ^9.2.13

#  cloud_firestore:



flutter:

  uses-material-design: true

  assets:
    - assets/Images/
    - assets/
    - assets/Images/Icons/
    - assets/bottomIcons/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/Fonts/Segoe UI.ttf
